var waterfall = [
  {
    "ID": 657,
    "SNO": 88,
    "NAME": "Lewis Rd. East Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Stoney Creek",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Stoney Creek-Winona",
    "HEIGHT_IN_M": 8,
    "WIDTH_IN_M": 5,
    "OWNERSHIP": "private",
    "ACCESS_FROM": "McNeilly Rd.",
    "LONGITUDE": -79.6650331672,
    "LATITUDE": 43.2011268358
  },
  {
    "ID": 630,
    "SNO": 27,
    "NAME": "Little Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Ancaster",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Tiffany-Coldwater",
    "HEIGHT_IN_M": 7,
    "WIDTH_IN_M": 3,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Wilson St. E.",
    "LONGITUDE": -79.9655785322,
    "LATITUDE": 43.2395466599
  },
  {
    "ID": 631,
    "SNO": 28,
    "NAME": "Tiffany Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Ancaster",
    "TYPE": "Waterfall",
    "RANKING": "A",
    "CLUSTER_AREA": "Tiffany-Coldwater",
    "HEIGHT_IN_M": 21,
    "WIDTH_IN_M": 6,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Wilson St. E. / Tiffany Falls CA",
    "LONGITUDE": -79.9581136523,
    "LATITUDE": 43.2381642354
  },
  {
    "ID": 636,
    "SNO": 33,
    "NAME": "Scenic Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Hamilton",
    "TYPE": "Cascade",
    "RANKING": "A",
    "CLUSTER_AREA": "Chedoke-Scenic",
    "HEIGHT_IN_M": 20,
    "WIDTH_IN_M": 6,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Scenic Dr. / Chedoke Radial Trail Head",
    "LONGITUDE": -79.9348050609,
    "LATITUDE": 43.2441807461
  },
  {
    "ID": 637,
    "SNO": 34,
    "NAME": "Lower Princess Falls",
    "ALTERNATE_NAME": "Lower Lang's Falls",
    "COMMUNITY": "Hamilton",
    "TYPE": "Cascade",
    "RANKING": "A",
    "CLUSTER_AREA": "Chedoke-Scenic",
    "HEIGHT_IN_M": 39.5,
    "WIDTH_IN_M": 3,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Hwy 403",
    "LONGITUDE": -79.929921264,
    "LATITUDE": 43.2459360829
  },
  {
    "ID": 638,
    "SNO": 35,
    "NAME": "Princess Falls",
    "ALTERNATE_NAME": "Lang's Falls, Upper Princess Falls, Westerly Falls on Chedoke Radial Trail",
    "COMMUNITY": "Hamilton",
    "TYPE": "Waterfall",
    "RANKING": "B",
    "CLUSTER_AREA": "Chedoke-Scenic",
    "HEIGHT_IN_M": 7,
    "WIDTH_IN_M": 2,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Scenic Dr. / Chedoke Radial Trail Land",
    "LONGITUDE": -79.9299229977,
    "LATITUDE": 43.2458370485
  },
  {
    "ID": 639,
    "SNO": 36,
    "NAME": "Upper Sanatorium Falls",
    "ALTERNATE_NAME": "Ravine Mountain Sanatorium, Sanatorium Falls",
    "COMMUNITY": "Hamilton",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Chedoke-Mountview",
    "HEIGHT_IN_M": 9,
    "WIDTH_IN_M": 3,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Sanatorium Rd. / Chedoke Civic Golf Course",
    "LONGITUDE": -79.9147017365,
    "LATITUDE": 43.2449462571
  },
  {
    "ID": 640,
    "SNO": 37,
    "NAME": "Lower Sanatorium Cascade",
    "ALTERNATE_NAME": "Lower Sanatorium Falls",
    "COMMUNITY": "Hamilton",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Chedoke-Mountview",
    "HEIGHT_IN_M": 4,
    "WIDTH_IN_M": 3,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Beddoe Dr. / Chedoke Civic Golf Course",
    "LONGITUDE": -79.9149542998,
    "LATITUDE": 43.2459841823
  },
  {
    "ID": 641,
    "SNO": 38,
    "NAME": "Mountview Falls",
    "ALTERNATE_NAME": "Goulding Falls, Water Fall on the Mountain, Easterly Falls on Chedoke Radial Trail",
    "COMMUNITY": "Hamilton",
    "TYPE": "Cascade",
    "RANKING": "B",
    "CLUSTER_AREA": "Chedoke-Mountview",
    "HEIGHT_IN_M": 10,
    "WIDTH_IN_M": 6,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Scenic Dr. / Chedoke Radial Trail Land",
    "LONGITUDE": -79.9214420692,
    "LATITUDE": 43.2454962606
  },
  {
    "ID": 642,
    "SNO": 39,
    "NAME": "Lower Westcliffe Falls",
    "ALTERNATE_NAME": "West Double Falls",
    "COMMUNITY": "Hamilton",
    "TYPE": "Cascade",
    "RANKING": "B",
    "CLUSTER_AREA": "West Chedoke",
    "HEIGHT_IN_M": 9,
    "WIDTH_IN_M": 6,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Beddoe Dr. / Chedoke Civic Golf Course",
    "LONGITUDE": -79.9084188429,
    "LATITUDE": 43.2456878806
  },
  {
    "ID": 643,
    "SNO": 40,
    "NAME": "Lower Cliffview Falls",
    "ALTERNATE_NAME": "East Double Falls",
    "COMMUNITY": "Hamilton",
    "TYPE": "Cascade",
    "RANKING": "B",
    "CLUSTER_AREA": "West Chedoke",
    "HEIGHT_IN_M": 4,
    "WIDTH_IN_M": 3,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Beddoe Dr. / Chedoke Civic Golf Course",
    "LONGITUDE": -79.9083575863,
    "LATITUDE": 43.2456692868
  },
  {
    "ID": 644,
    "SNO": 41,
    "NAME": "Westcliffe Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Hamilton",
    "TYPE": "Cascade",
    "RANKING": "A",
    "CLUSTER_AREA": "West Chedoke",
    "HEIGHT_IN_M": 15,
    "WIDTH_IN_M": 2,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Beddoe Dr. / Chedoke Civic Golf Course",
    "LONGITUDE": -79.9085225122,
    "LATITUDE": 43.2454007227
  },
  {
    "ID": 645,
    "SNO": 42,
    "NAME": "Cliffview Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Hamilton",
    "TYPE": "Cascade",
    "RANKING": "A",
    "CLUSTER_AREA": "West Chedoke",
    "HEIGHT_IN_M": 15,
    "WIDTH_IN_M": 3,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Beddoe Dr. / Chedoke Civic Golf Course / Scenic Dr. / Cliffview Park",
    "LONGITUDE": -79.9078531076,
    "LATITUDE": 43.2442597534
  },
  {
    "ID": 646,
    "SNO": 43,
    "NAME": "Lower Chedoke Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Hamilton",
    "TYPE": "Cascade",
    "RANKING": "A",
    "CLUSTER_AREA": "Chedoke",
    "HEIGHT_IN_M": 6,
    "WIDTH_IN_M": 11,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Beddoe Dr. / Chedoke Civic Golf Course",
    "LONGITUDE": -79.9004136818,
    "LATITUDE": 43.2442425069
  },
  {
    "ID": 648,
    "SNO": 45,
    "NAME": "Chedoke Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Hamilton",
    "TYPE": "Waterfall",
    "RANKING": "A",
    "CLUSTER_AREA": "Chedoke",
    "HEIGHT_IN_M": 18,
    "WIDTH_IN_M": 9,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Beddoe Dr. / Chedoke Civic Golf Course / Scenic Dr",
    "LONGITUDE": -79.9006560601,
    "LATITUDE": 43.241723548
  },
  {
    "ID": 649,
    "SNO": 46,
    "NAME": "Upper Glendale Falls",
    "ALTERNATE_NAME": "Glendale Falls",
    "COMMUNITY": "Hamilton",
    "TYPE": "Waterfall",
    "RANKING": "C",
    "CLUSTER_AREA": "Red Hill",
    "HEIGHT_IN_M": 3,
    "WIDTH_IN_M": 3,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Kingsview Dr.",
    "LONGITUDE": -79.8096628664,
    "LATITUDE": 43.2022730559
  },
  {
    "ID": 650,
    "SNO": 47,
    "NAME": "Buttermilk Falls",
    "ALTERNATE_NAME": "Inglis Falls",
    "COMMUNITY": "Hamilton",
    "TYPE": "Waterfall",
    "RANKING": "A",
    "CLUSTER_AREA": "Red Hill",
    "HEIGHT_IN_M": 23,
    "WIDTH_IN_M": 8,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Mountain Brow Blvd. / Oak-Knoll Park",
    "LONGITUDE": -79.8195743701,
    "LATITUDE": 43.2053202829
  },
  {
    "ID": 651,
    "SNO": 48,
    "NAME": "Albion Falls",
    "ALTERNATE_NAME": "Mount Albion Falls",
    "COMMUNITY": "Hamilton",
    "TYPE": "Cascade",
    "RANKING": "A",
    "CLUSTER_AREA": "Red Hill",
    "HEIGHT_IN_M": 19,
    "WIDTH_IN_M": 18,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Mountain Brow Blvd. / King's Forest Park",
    "LONGITUDE": -79.8196325793,
    "LATITUDE": 43.200386337
  },
  {
    "ID": 652,
    "SNO": 49,
    "NAME": "Little Davis Falls",
    "ALTERNATE_NAME": "Lower Felker's Falls",
    "COMMUNITY": "Hamilton",
    "TYPE": "Waterfall",
    "RANKING": "B",
    "CLUSTER_AREA": "Felker",
    "HEIGHT_IN_M": 3,
    "WIDTH_IN_M": 8,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Quigley Rd.",
    "LONGITUDE": -79.7889199226,
    "LATITUDE": 43.2067467435
  },
  {
    "ID": 653,
    "SNO": 50,
    "NAME": "Felker's Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Hamilton",
    "TYPE": "Waterfall",
    "RANKING": "A",
    "CLUSTER_AREA": "Felker",
    "HEIGHT_IN_M": 22,
    "WIDTH_IN_M": 6,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Ackland St. / Felker's Falls CA",
    "LONGITUDE": -79.7901531739,
    "LATITUDE": 43.2035181242
  },
  {
    "ID": 656,
    "SNO": 53,
    "NAME": "Billy Green Falls",
    "ALTERNATE_NAME": "Battlefield Falls",
    "COMMUNITY": "Stoney Creek",
    "TYPE": "Waterfall",
    "RANKING": "B",
    "CLUSTER_AREA": "Glover-Battlefield",
    "HEIGHT_IN_M": 17,
    "WIDTH_IN_M": 6,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Centennial Pky.",
    "LONGITUDE": -79.7665678321,
    "LATITUDE": 43.2072282806
  },
  {
    "ID": 658,
    "SNO": 89,
    "NAME": "Harvey Falls",
    "ALTERNATE_NAME": "Pond Falls",
    "COMMUNITY": "Stoney Creek",
    "TYPE": "Waterfall",
    "RANKING": "B",
    "CLUSTER_AREA": "Stoney Creek-Winona",
    "HEIGHT_IN_M": 16,
    "WIDTH_IN_M": 3,
    "OWNERSHIP": "private",
    "ACCESS_FROM": "Fifty Rd.",
    "LONGITUDE": -79.6591924909,
    "LATITUDE": 43.2002931303
  },
  {
    "ID": 659,
    "SNO": 90,
    "NAME": "Promontory Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Stoney Creek",
    "TYPE": "Waterfall",
    "RANKING": "B",
    "CLUSTER_AREA": "Stoney Creek-Winona",
    "HEIGHT_IN_M": 18,
    "WIDTH_IN_M": 1,
    "OWNERSHIP": "private",
    "ACCESS_FROM": "Fifty Rd.",
    "LONGITUDE": -79.6521676778,
    "LATITUDE": 43.1984636769
  },
  {
    "ID": 664,
    "SNO": 65,
    "NAME": "Jones Rd. Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Stoney Creek",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Stoney Creek-Vinemount",
    "HEIGHT_IN_M": 6,
    "WIDTH_IN_M": 2,
    "OWNERSHIP": "private",
    "ACCESS_FROM": "McNeilly Rd.",
    "LONGITUDE": -79.6956184367,
    "LATITUDE": 43.2035237423
  },
  {
    "ID": 665,
    "SNO": 66,
    "NAME": "Upper Quarry Cascade",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Flamborough",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Quarry",
    "HEIGHT_IN_M": 4,
    "WIDTH_IN_M": 1.2,
    "OWNERSHIP": "private",
    "ACCESS_FROM": "Mountain Brow Rd.",
    "LONGITUDE": -79.9064303328,
    "LATITUDE": 43.313419103
  },
  {
    "ID": 670,
    "SNO": 69,
    "NAME": "Lower Hopkins Cascade",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Flamborough",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Borer's",
    "HEIGHT_IN_M": 6,
    "WIDTH_IN_M": 3.5,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Valley Rd.",
    "LONGITUDE": -79.9292421585,
    "LATITUDE": 43.29663443
  },
  {
    "ID": 671,
    "SNO": 70,
    "NAME": "Rock Chapel Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Flamborough",
    "TYPE": "Waterfall",
    "RANKING": "C",
    "CLUSTER_AREA": "Borer's",
    "HEIGHT_IN_M": 8,
    "WIDTH_IN_M": 1.5,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Rock Chapel Rd.",
    "LONGITUDE": -79.936599457,
    "LATITUDE": 43.291120263
  },
  {
    "ID": 672,
    "SNO": 71,
    "NAME": "Dyment Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Flamborough",
    "TYPE": "Waterfall",
    "RANKING": "B",
    "CLUSTER_AREA": "Sydenham",
    "HEIGHT_IN_M": 15.7,
    "WIDTH_IN_M": 4,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Sydenham Rd. lookout",
    "LONGITUDE": -79.9491490037,
    "LATITUDE": 43.2781886653
  },
  {
    "ID": 675,
    "SNO": 74,
    "NAME": "East Greensville Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Flamborough",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Spencer-Logie's",
    "HEIGHT_IN_M": 5.5,
    "WIDTH_IN_M": 1.5,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Crooks Hollow Rd / Crooks Hollow CA",
    "LONGITUDE": -79.9914500959,
    "LATITUDE": 43.2794339243
  },
  {
    "ID": 679,
    "SNO": 81,
    "NAME": "East Iroquoia Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Hamilton",
    "TYPE": "Waterfall",
    "RANKING": "B",
    "CLUSTER_AREA": "Chedoke-Scenic",
    "HEIGHT_IN_M": 20,
    "WIDTH_IN_M": 1.2,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Hwy 403",
    "LONGITUDE": -79.938576055,
    "LATITUDE": 43.2447830911
  },
  {
    "ID": 680,
    "SNO": 82,
    "NAME": "Veevers Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Hamilton",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Felker",
    "HEIGHT_IN_M": 14,
    "WIDTH_IN_M": 2.5,
    "OWNERSHIP": "private",
    "ACCESS_FROM": "Greenhill Ave.",
    "LONGITUDE": -79.7809020324,
    "LATITUDE": 43.2081923618
  },
  {
    "ID": 681,
    "SNO": 83,
    "NAME": "Centennial Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Stoney Creek",
    "TYPE": "Cascade",
    "RANKING": "B",
    "CLUSTER_AREA": "Glover-Battlefield",
    "HEIGHT_IN_M": 10,
    "WIDTH_IN_M": 4,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Centennial Pky.",
    "LONGITUDE": -79.7684967945,
    "LATITUDE": 43.2086357768
  },
  {
    "ID": 682,
    "SNO": 111,
    "NAME": "Patterson West Cascade",
    "ALTERNATE_NAME": "Patterson Cascade",
    "COMMUNITY": "Dundas",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Borer's",
    "HEIGHT_IN_M": 4.3,
    "WIDTH_IN_M": 1.2,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Patterson Road",
    "LONGITUDE": -79.9277031202,
    "LATITUDE": 43.2979256672
  },
  {
    "ID": 683,
    "SNO": 112,
    "NAME": "Patterson East Cascade",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Dundas",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Borer's",
    "HEIGHT_IN_M": 4.6,
    "WIDTH_IN_M": 1.5,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Patterson Road",
    "LONGITUDE": -79.9270826916,
    "LATITUDE": 43.2981539663
  },
  {
    "ID": 684,
    "SNO": 113,
    "NAME": "Auchmar Falls",
    "ALTERNATE_NAME": "Upper Beckett Falls",
    "COMMUNITY": "Hamilton",
    "TYPE": "Waterfall",
    "RANKING": "C",
    "CLUSTER_AREA": "Chedoke",
    "HEIGHT_IN_M": 12,
    "WIDTH_IN_M": 1.5,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Beckett Drive",
    "LONGITUDE": -79.8911630415,
    "LATITUDE": 43.2435769109
  },
  {
    "ID": 691,
    "SNO": 87,
    "NAME": "Lewis Rd. West Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Stoney Creek",
    "TYPE": "Waterfall",
    "RANKING": "C",
    "CLUSTER_AREA": "Stoney Creek-Winona",
    "HEIGHT_IN_M": 9,
    "WIDTH_IN_M": 3,
    "OWNERSHIP": "private",
    "ACCESS_FROM": "McNeilly Rd.",
    "LONGITUDE": -79.6658182272,
    "LATITUDE": 43.2006857645
  },
  {
    "ID": 692,
    "SNO": 99,
    "NAME": "Beckett Falls",
    "ALTERNATE_NAME": "Lower Beckett Falls",
    "COMMUNITY": "Hamilton",
    "TYPE": "Waterfall",
    "RANKING": "C",
    "CLUSTER_AREA": "Chedoke",
    "HEIGHT_IN_M": 3,
    "WIDTH_IN_M": 1.2,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Beckett Drive",
    "LONGITUDE": -79.8858430904,
    "LATITUDE": 43.2448669005
  },
  {
    "ID": 695,
    "SNO": 91,
    "NAME": "Grand Cascade",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Stoney Creek",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Stoney Creek-Winona",
    "HEIGHT_IN_M": 4,
    "WIDTH_IN_M": 1,
    "OWNERSHIP": "private",
    "ACCESS_FROM": "Fifty Rd.",
    "LONGITUDE": -79.6493195,
    "LATITUDE": 43.1970163564
  },
  {
    "ID": 697,
    "SNO": 93,
    "NAME": "West of Fifty Upper Cascade",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Stoney Creek",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Stoney Creek-Winona",
    "HEIGHT_IN_M": 8,
    "WIDTH_IN_M": 1.5,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Fifty Rd.",
    "LONGITUDE": -79.6469336519,
    "LATITUDE": 43.1958175593
  },
  {
    "ID": 698,
    "SNO": 94,
    "NAME": "Fifty Rd. Cascade",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Stoney Creek",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Stoney Creek-Winona",
    "HEIGHT_IN_M": 10,
    "WIDTH_IN_M": 1.2,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Fifty Rd.",
    "LONGITUDE": -79.6444339199,
    "LATITUDE": 43.1953197232
  },
  {
    "ID": 699,
    "SNO": 95,
    "NAME": "East of Fifty Falls",
    "ALTERNATE_NAME": "Winona Falls",
    "COMMUNITY": "Stoney Creek",
    "TYPE": "Waterfall",
    "RANKING": "C",
    "CLUSTER_AREA": "Stoney Creek-Winona",
    "HEIGHT_IN_M": 10,
    "WIDTH_IN_M": 1.5,
    "OWNERSHIP": "private",
    "ACCESS_FROM": "Fifty Rd.",
    "LONGITUDE": -79.6414150577,
    "LATITUDE": 43.1949237233
  },
  {
    "ID": 700,
    "SNO": 96,
    "NAME": "Puddicombe Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Stoney Creek",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Stoney Creek-Winona",
    "HEIGHT_IN_M": 6,
    "WIDTH_IN_M": 2,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Fifty Rd.",
    "LONGITUDE": -79.6379414744,
    "LATITUDE": 43.1950535025
  },
  {
    "ID": 702,
    "SNO": 103,
    "NAME": "Heritage Green Falls",
    "ALTERNATE_NAME": "Taro Falls",
    "COMMUNITY": "Hamilton",
    "TYPE": "Waterfall",
    "RANKING": "B",
    "CLUSTER_AREA": "Felker",
    "HEIGHT_IN_M": 12.2,
    "WIDTH_IN_M": 1.8,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Ackland Street",
    "LONGITUDE": -79.7875197394,
    "LATITUDE": 43.2047238769
  },
  {
    "ID": 705,
    "SNO": 109,
    "NAME": "Middle Glendale Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Hamilton",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Red Hill",
    "HEIGHT_IN_M": 3.1,
    "WIDTH_IN_M": 3.4,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Bruce Trail",
    "LONGITUDE": -79.8094123597,
    "LATITUDE": 43.202495565
  },
  {
    "ID": 706,
    "SNO": 110,
    "NAME": "Mountain Spring Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Hamilton",
    "TYPE": "Waterfall",
    "RANKING": "B",
    "CLUSTER_AREA": "Felker",
    "HEIGHT_IN_M": 15,
    "WIDTH_IN_M": 2.4,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Ackland Street",
    "LONGITUDE": -79.787954758,
    "LATITUDE": 43.2045123758
  },
  {
    "ID": 709,
    "SNO": 107,
    "NAME": "Valley Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Flamborough",
    "TYPE": "Waterfall",
    "RANKING": "C",
    "CLUSTER_AREA": "Borer's",
    "HEIGHT_IN_M": 4.3,
    "WIDTH_IN_M": 4.3,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Bruce Trail at Valley Road",
    "LONGITUDE": -79.9282532241,
    "LATITUDE": 43.2974896017
  },
  {
    "ID": 719,
    "SNO": 123,
    "NAME": "Pritchard Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Hamilton",
    "TYPE": "Waterfall",
    "RANKING": "C",
    "CLUSTER_AREA": "Red Hill",
    "HEIGHT_IN_M": 4.5,
    "WIDTH_IN_M": 1,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Mountain Brow Blvd. / King's Forest Park",
    "LONGITUDE": -79.8163322218,
    "LATITUDE": 43.2011086249
  },
  {
    "ID": 720,
    "SNO": 126,
    "NAME": "Billy Monkley Cascade",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Hamilton",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Red Hill",
    "HEIGHT_IN_M": 3,
    "WIDTH_IN_M": 6.4,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Chippewa Rail Trail via Rymal Road/Billy Monkley Bird Sanctuary",
    "LONGITUDE": -79.8304455843,
    "LATITUDE": 43.1904031768
  },
  {
    "ID": 721,
    "SNO": 122,
    "NAME": "Broman Falls",
    "ALTERNATE_NAME": "Coop's Falls",
    "COMMUNITY": "Hamilton",
    "TYPE": "Waterfall",
    "RANKING": "C",
    "CLUSTER_AREA": "Red Hill",
    "HEIGHT_IN_M": 7,
    "WIDTH_IN_M": 1.1,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Bruce Trail Escarpment Rail Trail at Mohawk Sports Park",
    "LONGITUDE": -79.816004324,
    "LATITUDE": 43.2142429997
  },
  {
    "ID": 725,
    "SNO": 130,
    "NAME": "Baby Albion Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Hamilton",
    "TYPE": "Waterfall",
    "RANKING": "C",
    "CLUSTER_AREA": "Red Hill",
    "HEIGHT_IN_M": 8.5,
    "WIDTH_IN_M": 1,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Mountain Brow Blvd. / King's Forest Park",
    "LONGITUDE": -79.8196615308,
    "LATITUDE": 43.2001615195
  },
  {
    "ID": 726,
    "SNO": 54,
    "NAME": "Lower Punchbowl Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Stoney Creek",
    "TYPE": "Waterfall",
    "RANKING": "B",
    "CLUSTER_AREA": "Punchbowl",
    "HEIGHT_IN_M": 6,
    "WIDTH_IN_M": 6,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Mountain Ave.",
    "LONGITUDE": -79.7571684375,
    "LATITUDE": 43.2112056373
  },
  {
    "ID": 727,
    "SNO": 55,
    "NAME": "Devil's Punchbowl Falls",
    "ALTERNATE_NAME": "Horseshoe Falls, Devil's Punch Bowl",
    "COMMUNITY": "Stoney Creek",
    "TYPE": "Waterfall",
    "RANKING": "A",
    "CLUSTER_AREA": "Punchbowl",
    "HEIGHT_IN_M": 37,
    "WIDTH_IN_M": 3,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Ridge Rd. / Devil's Punchbowl CA",
    "LONGITUDE": -79.7559056059,
    "LATITUDE": 43.2103454752
  },
  {
    "ID": 729,
    "SNO": 57,
    "NAME": "Dewitt Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Stoney Creek",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Stoney Creek-Fruitland",
    "HEIGHT_IN_M": 7,
    "WIDTH_IN_M": 2,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Dewitt Rd.",
    "LONGITUDE": -79.718432469,
    "LATITUDE": 43.2068071715
  },
  {
    "ID": 733,
    "SNO": 78,
    "NAME": "Lower Little Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Ancaster",
    "TYPE": "Cascade",
    "RANKING": "B",
    "CLUSTER_AREA": "Tiffany-Coldwater",
    "HEIGHT_IN_M": 8.2,
    "WIDTH_IN_M": 1.8,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Wilson St. E.",
    "LONGITUDE": -79.9657556367,
    "LATITUDE": 43.2399984923
  },
  {
    "ID": 734,
    "SNO": 79,
    "NAME": "Ancaster Heights Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Ancaster",
    "TYPE": "Cascade",
    "RANKING": "B",
    "CLUSTER_AREA": "Tiffany-Coldwater",
    "HEIGHT_IN_M": 13.4,
    "WIDTH_IN_M": 1.8,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Wilson St. E.",
    "LONGITUDE": -79.9628410216,
    "LATITUDE": 43.2397379821
  },
  {
    "ID": 735,
    "SNO": 80,
    "NAME": "West Iroquoia Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Hamilton",
    "TYPE": "Waterfall",
    "RANKING": "B",
    "CLUSTER_AREA": "Chedoke-Scenic",
    "HEIGHT_IN_M": 19.8,
    "WIDTH_IN_M": 1,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Hwy 403",
    "LONGITUDE": -79.9404919918,
    "LATITUDE": 43.2443956465
  },
  {
    "ID": 743,
    "SNO": 138,
    "NAME": "Sugar Shack Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Dundas",
    "TYPE": "Waterfall",
    "RANKING": "B",
    "CLUSTER_AREA": "Borer's",
    "HEIGHT_IN_M": 9,
    "WIDTH_IN_M": 4,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Rock Chapel Rd. / Rock Chapel Sanctuary",
    "LONGITUDE": -79.9375407317,
    "LATITUDE": 43.2844926642
  },
  {
    "ID": 602,
    "SNO": 1,
    "NAME": "Progreston Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Flamborough",
    "TYPE": "Waterfall",
    "RANKING": "A",
    "CLUSTER_AREA": "Bronte",
    "HEIGHT_IN_M": 6.7,
    "WIDTH_IN_M": 16.5,
    "OWNERSHIP": "private",
    "ACCESS_FROM": "Progreston Rd.",
    "LONGITUDE": -79.9599213686,
    "LATITUDE": 43.3981005764
  },
  {
    "ID": 604,
    "SNO": 3,
    "NAME": "Great Falls",
    "ALTERNATE_NAME": "Waterdown Falls, Grindstone Falls, Smokey Hollow Falls, Dunn's Falls, The Falls, Palmer's Falls",
    "COMMUNITY": "Flamborough",
    "TYPE": "Waterfall",
    "RANKING": "A",
    "CLUSTER_AREA": "Grindstone",
    "HEIGHT_IN_M": 10,
    "WIDTH_IN_M": 5,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Mill St / Smokey Hollow Resource Management Area",
    "LONGITUDE": -79.8872384751,
    "LATITUDE": 43.3305405932
  },
  {
    "ID": 605,
    "SNO": 4,
    "NAME": "Grindstone Cascade",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Flamborough",
    "TYPE": "Cascade",
    "RANKING": "B",
    "CLUSTER_AREA": "Grindstone",
    "HEIGHT_IN_M": 3,
    "WIDTH_IN_M": 5,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Mill St / Smokey Hollow Resource Management Area",
    "LONGITUDE": -79.886919138,
    "LATITUDE": 43.3284394445
  },
  {
    "ID": 609,
    "SNO": 6,
    "NAME": "Borer's Falls",
    "ALTERNATE_NAME": "Rock Chapel Falls",
    "COMMUNITY": "Flamborough",
    "TYPE": "Waterfall",
    "RANKING": "A",
    "CLUSTER_AREA": "Borer's",
    "HEIGHT_IN_M": 15,
    "WIDTH_IN_M": 5,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Rock Chapel Rd. / Rock Chapel Sanctuary",
    "LONGITUDE": -79.9367867327,
    "LATITUDE": 43.2938143596
  },
  {
    "ID": 613,
    "SNO": 10,
    "NAME": "Lower Sydenham Falls",
    "ALTERNATE_NAME": "Sydenham Ravine",
    "COMMUNITY": "Dundas",
    "TYPE": "Waterfall",
    "RANKING": "B",
    "CLUSTER_AREA": "Sydenham",
    "HEIGHT_IN_M": 4,
    "WIDTH_IN_M": 4,
    "OWNERSHIP": "private",
    "ACCESS_FROM": "Livingstone Dr. / Cascades Park",
    "LONGITUDE": -79.9583534541,
    "LATITUDE": 43.2739596762
  },
  {
    "ID": 614,
    "SNO": 11,
    "NAME": "Tew's Falls",
    "ALTERNATE_NAME": "Hopkins Falls, Tunis Falls",
    "COMMUNITY": "Flamborough",
    "TYPE": "Waterfall",
    "RANKING": "A",
    "CLUSTER_AREA": "Spencer-Logie's",
    "HEIGHT_IN_M": 41,
    "WIDTH_IN_M": 9,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Harvest Rd. / Spencer Gorge / Webster's Falls CA",
    "LONGITUDE": -79.9782660679,
    "LATITUDE": 43.2807126185
  },
  {
    "ID": 616,
    "SNO": 13,
    "NAME": "Webster's Falls",
    "ALTERNATE_NAME": "Spencer Falls, Hatt's Falls",
    "COMMUNITY": "Flamborough",
    "TYPE": "Waterfall",
    "RANKING": "A",
    "CLUSTER_AREA": "Spencer-Logie's",
    "HEIGHT_IN_M": 22,
    "WIDTH_IN_M": 30,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Fallsview Rd. / Spencer Gorge / Webster's Falls CA",
    "LONGITUDE": -79.98091776,
    "LATITUDE": 43.2761709621
  },
  {
    "ID": 617,
    "SNO": 14,
    "NAME": "Baby Webster's Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Flamborough",
    "TYPE": "Waterfall",
    "RANKING": "B",
    "CLUSTER_AREA": "Spencer-Logie's",
    "HEIGHT_IN_M": 9,
    "WIDTH_IN_M": 3,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Fallsview Rd. / Spencer Gorge / Webster's Falls CA",
    "LONGITUDE": -79.9818994596,
    "LATITUDE": 43.2756844534
  },
  {
    "ID": 618,
    "SNO": 15,
    "NAME": "Darnley Cascade",
    "ALTERNATE_NAME": "Stutt's Falls, Crooks Hollow Falls",
    "COMMUNITY": "Flamborough",
    "TYPE": "Cascade",
    "RANKING": "A",
    "CLUSTER_AREA": "Spencer-Logie's",
    "HEIGHT_IN_M": 4,
    "WIDTH_IN_M": 22,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Crooks Hollow Rd / Darnley Mill ruins",
    "LONGITUDE": -80.0067933954,
    "LATITUDE": 43.2772089908
  },
  {
    "ID": 619,
    "SNO": 16,
    "NAME": "Dundas Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Dundas",
    "TYPE": "Waterfall",
    "RANKING": "B",
    "CLUSTER_AREA": "Spencer-Logie's",
    "HEIGHT_IN_M": 6.4,
    "WIDTH_IN_M": 6.7,
    "OWNERSHIP": "private",
    "ACCESS_FROM": "King St.",
    "LONGITUDE": -79.9721588727,
    "LATITUDE": 43.273040039
  },
  {
    "ID": 621,
    "SNO": 18,
    "NAME": "Mineral Springs Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Ancaster",
    "TYPE": "Cascade",
    "RANKING": "B",
    "CLUSTER_AREA": "DV-Sulphur",
    "HEIGHT_IN_M": 3,
    "WIDTH_IN_M": 2,
    "OWNERSHIP": "private",
    "ACCESS_FROM": "Must view from owner's driveway only",
    "LONGITUDE": -80.0124449458,
    "LATITUDE": 43.2363680324
  },
  {
    "ID": 622,
    "SNO": 19,
    "NAME": "Hermitage Cascade",
    "ALTERNATE_NAME": "Hermitage Falls",
    "COMMUNITY": "Ancaster",
    "TYPE": "Cascade",
    "RANKING": "B",
    "CLUSTER_AREA": "DV-Sulphur",
    "HEIGHT_IN_M": 4,
    "WIDTH_IN_M": 5,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Sulphur Springs Rd. / Hermitage ruins",
    "LONGITUDE": -79.9980353555,
    "LATITUDE": 43.2363687865
  },
  {
    "ID": 623,
    "SNO": 20,
    "NAME": "Heritage Falls",
    "ALTERNATE_NAME": "Griffin Falls",
    "COMMUNITY": "Ancaster",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "DV-Sulphur",
    "HEIGHT_IN_M": 5,
    "WIDTH_IN_M": 3,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Sulphur Springs Rd. / Hermitage ruins",
    "LONGITUDE": -80.0037779538,
    "LATITUDE": 43.2399397533
  },
  {
    "ID": 624,
    "SNO": 21,
    "NAME": "Mill Falls",
    "ALTERNATE_NAME": "Wilson Falls, Mill Stream Waterfall, Upper Mill Falls",
    "COMMUNITY": "Ancaster",
    "TYPE": "Waterfall",
    "RANKING": "B",
    "CLUSTER_AREA": "Ancaster-Sulphur",
    "HEIGHT_IN_M": 7,
    "WIDTH_IN_M": 4,
    "OWNERSHIP": "private",
    "ACCESS_FROM": "Old Dundas Rd. / Old Mill Rest.",
    "LONGITUDE": -79.9738975614,
    "LATITUDE": 43.2333543686
  },
  {
    "ID": 625,
    "SNO": 22,
    "NAME": "Lower Mill Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Ancaster",
    "TYPE": "Cascade",
    "RANKING": "B",
    "CLUSTER_AREA": "Ancaster-Sulphur",
    "HEIGHT_IN_M": 6,
    "WIDTH_IN_M": 4,
    "OWNERSHIP": "private",
    "ACCESS_FROM": "Old Dundas Rd. / Old Mill Rest.",
    "LONGITUDE": -79.9735174294,
    "LATITUDE": 43.2339902868
  },
  {
    "ID": 626,
    "SNO": 23,
    "NAME": "Canterbury Falls",
    "ALTERNATE_NAME": "Milne Falls",
    "COMMUNITY": "Ancaster",
    "TYPE": "Cascade",
    "RANKING": "B",
    "CLUSTER_AREA": "Ancaster-Sulphur",
    "HEIGHT_IN_M": 9,
    "WIDTH_IN_M": 4,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Old Dundas Rd.",
    "LONGITUDE": -79.9806967142,
    "LATITUDE": 43.2369809903
  },
  {
    "ID": 627,
    "SNO": 24,
    "NAME": "Little Canterbury Falls",
    "ALTERNATE_NAME": "N/A",
    "COMMUNITY": "Ancaster",
    "TYPE": "Cascade",
    "RANKING": "C",
    "CLUSTER_AREA": "Ancaster-Sulphur",
    "HEIGHT_IN_M": 5,
    "WIDTH_IN_M": 2,
    "OWNERSHIP": "public",
    "ACCESS_FROM": "Old Dundas Rd.",
    "LONGITUDE": -79.9800207868,
    "LATITUDE": 43.2368939235
  },
  {
    "ID": 629,
    "SNO": 26,
    "NAME": "Sherman Falls",
    "ALTERNATE_NAME": "Smith's Falls, Whitton Falls, Fairy Falls, Angel Falls",
    "COMMUNITY": "Ancaster",
    "TYPE": "Waterfall",
    "RANKING": "A",
    "CLUSTER_AREA": "Ancaster-Sulphur",
    "HEIGHT_IN_M": 17,
    "WIDTH_IN_M": 8,
    "OWNERSHIP": "private",
    "ACCESS_FROM": "Lions Club Rd.",
    "LONGITUDE": -79.9729308523,
    "LATITUDE": 43.2381181449
  }
]